Update customization_dev.groovy: use abs path to ui_layout.xml in update_ui_layout()
Hi @briacp I was getting the following error in the `update_ui_layout`: 

```
download_asset: https://raw.githubusercontent.com/capstanlqc/omegat-user-config/master/uiLayout.xml
remote_file_name: uiLayout.xml
file_location_rel_path_str: uiLayout.xml
local_path_to_location: /home/souto/.omegat610-dev-custom/uiLayout.xml
>> DOWNLOAD uiLayout.xml to uiLayout.xml
%% local_file: /home/souto/.omegat610-dev-custom/uiLayout.xml
<<<< HANDLING UI LAYOUT >>>>>
An error occurred
javax.script.ScriptException: javax.script.ScriptException: java.io.FileNotFoundException: uiLayout.xml (No such file or directory)
```

If I understand what this function tries to do, I think that's because it was trying to use the file name (or relative path to the file) and it couldn't find the file. 

I have used the absolute path to the local file as a argument to the function, and it seems to work now. Could you please review that this is the intended logic? Thank you.